// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ksoft/seat_management_pb/seat_management.proto

package ksoft.seat_management_pb;

public final class SeatManagement {
  private SeatManagement() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetUserStatusRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ksoft.seat_management_pb.GetUserStatusRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ksoft.khulnasoft_common.Metadata metadata = 1 [json_name = "metadata"];</code>
     * @return Whether the metadata field is set.
     */
    boolean hasMetadata();
    /**
     * <code>.ksoft.khulnasoft_common.Metadata metadata = 1 [json_name = "metadata"];</code>
     * @return The metadata.
     */
    ksoft.khulnasoft_common.KhulnasoftCommon.Metadata getMetadata();
    /**
     * <code>.ksoft.khulnasoft_common.Metadata metadata = 1 [json_name = "metadata"];</code>
     */
    ksoft.khulnasoft_common.KhulnasoftCommon.MetadataOrBuilder getMetadataOrBuilder();
  }
  /**
   * Protobuf type {@code ksoft.seat_management_pb.GetUserStatusRequest}
   */
  public static final class GetUserStatusRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ksoft.seat_management_pb.GetUserStatusRequest)
      GetUserStatusRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetUserStatusRequest.newBuilder() to construct.
    private GetUserStatusRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetUserStatusRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetUserStatusRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ksoft.seat_management_pb.SeatManagement.internal_static_ksoft_seat_management_pb_GetUserStatusRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ksoft.seat_management_pb.SeatManagement.internal_static_ksoft_seat_management_pb_GetUserStatusRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest.class, ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest.Builder.class);
    }

    public static final int METADATA_FIELD_NUMBER = 1;
    private ksoft.khulnasoft_common.KhulnasoftCommon.Metadata metadata_;
    /**
     * <code>.ksoft.khulnasoft_common.Metadata metadata = 1 [json_name = "metadata"];</code>
     * @return Whether the metadata field is set.
     */
    @java.lang.Override
    public boolean hasMetadata() {
      return metadata_ != null;
    }
    /**
     * <code>.ksoft.khulnasoft_common.Metadata metadata = 1 [json_name = "metadata"];</code>
     * @return The metadata.
     */
    @java.lang.Override
    public ksoft.khulnasoft_common.KhulnasoftCommon.Metadata getMetadata() {
      return metadata_ == null ? ksoft.khulnasoft_common.KhulnasoftCommon.Metadata.getDefaultInstance() : metadata_;
    }
    /**
     * <code>.ksoft.khulnasoft_common.Metadata metadata = 1 [json_name = "metadata"];</code>
     */
    @java.lang.Override
    public ksoft.khulnasoft_common.KhulnasoftCommon.MetadataOrBuilder getMetadataOrBuilder() {
      return getMetadata();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (metadata_ != null) {
        output.writeMessage(1, getMetadata());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (metadata_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMetadata());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest)) {
        return super.equals(obj);
      }
      ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest other = (ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest) obj;

      if (hasMetadata() != other.hasMetadata()) return false;
      if (hasMetadata()) {
        if (!getMetadata()
            .equals(other.getMetadata())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMetadata()) {
        hash = (37 * hash) + METADATA_FIELD_NUMBER;
        hash = (53 * hash) + getMetadata().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ksoft.seat_management_pb.GetUserStatusRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ksoft.seat_management_pb.GetUserStatusRequest)
        ksoft.seat_management_pb.SeatManagement.GetUserStatusRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ksoft.seat_management_pb.SeatManagement.internal_static_ksoft_seat_management_pb_GetUserStatusRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ksoft.seat_management_pb.SeatManagement.internal_static_ksoft_seat_management_pb_GetUserStatusRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest.class, ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest.Builder.class);
      }

      // Construct using ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (metadataBuilder_ == null) {
          metadata_ = null;
        } else {
          metadata_ = null;
          metadataBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ksoft.seat_management_pb.SeatManagement.internal_static_ksoft_seat_management_pb_GetUserStatusRequest_descriptor;
      }

      @java.lang.Override
      public ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest getDefaultInstanceForType() {
        return ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest build() {
        ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest buildPartial() {
        ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest result = new ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest(this);
        if (metadataBuilder_ == null) {
          result.metadata_ = metadata_;
        } else {
          result.metadata_ = metadataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest) {
          return mergeFrom((ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest other) {
        if (other == ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest.getDefaultInstance()) return this;
        if (other.hasMetadata()) {
          mergeMetadata(other.getMetadata());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getMetadataFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private ksoft.khulnasoft_common.KhulnasoftCommon.Metadata metadata_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ksoft.khulnasoft_common.KhulnasoftCommon.Metadata, ksoft.khulnasoft_common.KhulnasoftCommon.Metadata.Builder, ksoft.khulnasoft_common.KhulnasoftCommon.MetadataOrBuilder> metadataBuilder_;
      /**
       * <code>.ksoft.khulnasoft_common.Metadata metadata = 1 [json_name = "metadata"];</code>
       * @return Whether the metadata field is set.
       */
      public boolean hasMetadata() {
        return metadataBuilder_ != null || metadata_ != null;
      }
      /**
       * <code>.ksoft.khulnasoft_common.Metadata metadata = 1 [json_name = "metadata"];</code>
       * @return The metadata.
       */
      public ksoft.khulnasoft_common.KhulnasoftCommon.Metadata getMetadata() {
        if (metadataBuilder_ == null) {
          return metadata_ == null ? ksoft.khulnasoft_common.KhulnasoftCommon.Metadata.getDefaultInstance() : metadata_;
        } else {
          return metadataBuilder_.getMessage();
        }
      }
      /**
       * <code>.ksoft.khulnasoft_common.Metadata metadata = 1 [json_name = "metadata"];</code>
       */
      public Builder setMetadata(ksoft.khulnasoft_common.KhulnasoftCommon.Metadata value) {
        if (metadataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          metadata_ = value;
          onChanged();
        } else {
          metadataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ksoft.khulnasoft_common.Metadata metadata = 1 [json_name = "metadata"];</code>
       */
      public Builder setMetadata(
          ksoft.khulnasoft_common.KhulnasoftCommon.Metadata.Builder builderForValue) {
        if (metadataBuilder_ == null) {
          metadata_ = builderForValue.build();
          onChanged();
        } else {
          metadataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ksoft.khulnasoft_common.Metadata metadata = 1 [json_name = "metadata"];</code>
       */
      public Builder mergeMetadata(ksoft.khulnasoft_common.KhulnasoftCommon.Metadata value) {
        if (metadataBuilder_ == null) {
          if (metadata_ != null) {
            metadata_ =
              ksoft.khulnasoft_common.KhulnasoftCommon.Metadata.newBuilder(metadata_).mergeFrom(value).buildPartial();
          } else {
            metadata_ = value;
          }
          onChanged();
        } else {
          metadataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ksoft.khulnasoft_common.Metadata metadata = 1 [json_name = "metadata"];</code>
       */
      public Builder clearMetadata() {
        if (metadataBuilder_ == null) {
          metadata_ = null;
          onChanged();
        } else {
          metadata_ = null;
          metadataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ksoft.khulnasoft_common.Metadata metadata = 1 [json_name = "metadata"];</code>
       */
      public ksoft.khulnasoft_common.KhulnasoftCommon.Metadata.Builder getMetadataBuilder() {
        
        onChanged();
        return getMetadataFieldBuilder().getBuilder();
      }
      /**
       * <code>.ksoft.khulnasoft_common.Metadata metadata = 1 [json_name = "metadata"];</code>
       */
      public ksoft.khulnasoft_common.KhulnasoftCommon.MetadataOrBuilder getMetadataOrBuilder() {
        if (metadataBuilder_ != null) {
          return metadataBuilder_.getMessageOrBuilder();
        } else {
          return metadata_ == null ?
              ksoft.khulnasoft_common.KhulnasoftCommon.Metadata.getDefaultInstance() : metadata_;
        }
      }
      /**
       * <code>.ksoft.khulnasoft_common.Metadata metadata = 1 [json_name = "metadata"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ksoft.khulnasoft_common.KhulnasoftCommon.Metadata, ksoft.khulnasoft_common.KhulnasoftCommon.Metadata.Builder, ksoft.khulnasoft_common.KhulnasoftCommon.MetadataOrBuilder> 
          getMetadataFieldBuilder() {
        if (metadataBuilder_ == null) {
          metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ksoft.khulnasoft_common.KhulnasoftCommon.Metadata, ksoft.khulnasoft_common.KhulnasoftCommon.Metadata.Builder, ksoft.khulnasoft_common.KhulnasoftCommon.MetadataOrBuilder>(
                  getMetadata(),
                  getParentForChildren(),
                  isClean());
          metadata_ = null;
        }
        return metadataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ksoft.seat_management_pb.GetUserStatusRequest)
    }

    // @@protoc_insertion_point(class_scope:ksoft.seat_management_pb.GetUserStatusRequest)
    private static final ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest();
    }

    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetUserStatusRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetUserStatusRequest>() {
      @java.lang.Override
      public GetUserStatusRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetUserStatusRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetUserStatusRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ksoft.seat_management_pb.SeatManagement.GetUserStatusRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetUserStatusResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ksoft.seat_management_pb.GetUserStatusResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ksoft.khulnasoft_common.UserStatus user_status = 1 [json_name = "userStatus"];</code>
     * @return Whether the userStatus field is set.
     */
    boolean hasUserStatus();
    /**
     * <code>.ksoft.khulnasoft_common.UserStatus user_status = 1 [json_name = "userStatus"];</code>
     * @return The userStatus.
     */
    ksoft.khulnasoft_common.KhulnasoftCommon.UserStatus getUserStatus();
    /**
     * <code>.ksoft.khulnasoft_common.UserStatus user_status = 1 [json_name = "userStatus"];</code>
     */
    ksoft.khulnasoft_common.KhulnasoftCommon.UserStatusOrBuilder getUserStatusOrBuilder();
  }
  /**
   * Protobuf type {@code ksoft.seat_management_pb.GetUserStatusResponse}
   */
  public static final class GetUserStatusResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ksoft.seat_management_pb.GetUserStatusResponse)
      GetUserStatusResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetUserStatusResponse.newBuilder() to construct.
    private GetUserStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetUserStatusResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetUserStatusResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ksoft.seat_management_pb.SeatManagement.internal_static_ksoft_seat_management_pb_GetUserStatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ksoft.seat_management_pb.SeatManagement.internal_static_ksoft_seat_management_pb_GetUserStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse.class, ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse.Builder.class);
    }

    public static final int USER_STATUS_FIELD_NUMBER = 1;
    private ksoft.khulnasoft_common.KhulnasoftCommon.UserStatus userStatus_;
    /**
     * <code>.ksoft.khulnasoft_common.UserStatus user_status = 1 [json_name = "userStatus"];</code>
     * @return Whether the userStatus field is set.
     */
    @java.lang.Override
    public boolean hasUserStatus() {
      return userStatus_ != null;
    }
    /**
     * <code>.ksoft.khulnasoft_common.UserStatus user_status = 1 [json_name = "userStatus"];</code>
     * @return The userStatus.
     */
    @java.lang.Override
    public ksoft.khulnasoft_common.KhulnasoftCommon.UserStatus getUserStatus() {
      return userStatus_ == null ? ksoft.khulnasoft_common.KhulnasoftCommon.UserStatus.getDefaultInstance() : userStatus_;
    }
    /**
     * <code>.ksoft.khulnasoft_common.UserStatus user_status = 1 [json_name = "userStatus"];</code>
     */
    @java.lang.Override
    public ksoft.khulnasoft_common.KhulnasoftCommon.UserStatusOrBuilder getUserStatusOrBuilder() {
      return getUserStatus();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userStatus_ != null) {
        output.writeMessage(1, getUserStatus());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userStatus_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUserStatus());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse)) {
        return super.equals(obj);
      }
      ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse other = (ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse) obj;

      if (hasUserStatus() != other.hasUserStatus()) return false;
      if (hasUserStatus()) {
        if (!getUserStatus()
            .equals(other.getUserStatus())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUserStatus()) {
        hash = (37 * hash) + USER_STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getUserStatus().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ksoft.seat_management_pb.GetUserStatusResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ksoft.seat_management_pb.GetUserStatusResponse)
        ksoft.seat_management_pb.SeatManagement.GetUserStatusResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ksoft.seat_management_pb.SeatManagement.internal_static_ksoft_seat_management_pb_GetUserStatusResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ksoft.seat_management_pb.SeatManagement.internal_static_ksoft_seat_management_pb_GetUserStatusResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse.class, ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse.Builder.class);
      }

      // Construct using ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (userStatusBuilder_ == null) {
          userStatus_ = null;
        } else {
          userStatus_ = null;
          userStatusBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ksoft.seat_management_pb.SeatManagement.internal_static_ksoft_seat_management_pb_GetUserStatusResponse_descriptor;
      }

      @java.lang.Override
      public ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse getDefaultInstanceForType() {
        return ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse.getDefaultInstance();
      }

      @java.lang.Override
      public ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse build() {
        ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse buildPartial() {
        ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse result = new ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse(this);
        if (userStatusBuilder_ == null) {
          result.userStatus_ = userStatus_;
        } else {
          result.userStatus_ = userStatusBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse) {
          return mergeFrom((ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse other) {
        if (other == ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse.getDefaultInstance()) return this;
        if (other.hasUserStatus()) {
          mergeUserStatus(other.getUserStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getUserStatusFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private ksoft.khulnasoft_common.KhulnasoftCommon.UserStatus userStatus_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ksoft.khulnasoft_common.KhulnasoftCommon.UserStatus, ksoft.khulnasoft_common.KhulnasoftCommon.UserStatus.Builder, ksoft.khulnasoft_common.KhulnasoftCommon.UserStatusOrBuilder> userStatusBuilder_;
      /**
       * <code>.ksoft.khulnasoft_common.UserStatus user_status = 1 [json_name = "userStatus"];</code>
       * @return Whether the userStatus field is set.
       */
      public boolean hasUserStatus() {
        return userStatusBuilder_ != null || userStatus_ != null;
      }
      /**
       * <code>.ksoft.khulnasoft_common.UserStatus user_status = 1 [json_name = "userStatus"];</code>
       * @return The userStatus.
       */
      public ksoft.khulnasoft_common.KhulnasoftCommon.UserStatus getUserStatus() {
        if (userStatusBuilder_ == null) {
          return userStatus_ == null ? ksoft.khulnasoft_common.KhulnasoftCommon.UserStatus.getDefaultInstance() : userStatus_;
        } else {
          return userStatusBuilder_.getMessage();
        }
      }
      /**
       * <code>.ksoft.khulnasoft_common.UserStatus user_status = 1 [json_name = "userStatus"];</code>
       */
      public Builder setUserStatus(ksoft.khulnasoft_common.KhulnasoftCommon.UserStatus value) {
        if (userStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userStatus_ = value;
          onChanged();
        } else {
          userStatusBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ksoft.khulnasoft_common.UserStatus user_status = 1 [json_name = "userStatus"];</code>
       */
      public Builder setUserStatus(
          ksoft.khulnasoft_common.KhulnasoftCommon.UserStatus.Builder builderForValue) {
        if (userStatusBuilder_ == null) {
          userStatus_ = builderForValue.build();
          onChanged();
        } else {
          userStatusBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ksoft.khulnasoft_common.UserStatus user_status = 1 [json_name = "userStatus"];</code>
       */
      public Builder mergeUserStatus(ksoft.khulnasoft_common.KhulnasoftCommon.UserStatus value) {
        if (userStatusBuilder_ == null) {
          if (userStatus_ != null) {
            userStatus_ =
              ksoft.khulnasoft_common.KhulnasoftCommon.UserStatus.newBuilder(userStatus_).mergeFrom(value).buildPartial();
          } else {
            userStatus_ = value;
          }
          onChanged();
        } else {
          userStatusBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ksoft.khulnasoft_common.UserStatus user_status = 1 [json_name = "userStatus"];</code>
       */
      public Builder clearUserStatus() {
        if (userStatusBuilder_ == null) {
          userStatus_ = null;
          onChanged();
        } else {
          userStatus_ = null;
          userStatusBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ksoft.khulnasoft_common.UserStatus user_status = 1 [json_name = "userStatus"];</code>
       */
      public ksoft.khulnasoft_common.KhulnasoftCommon.UserStatus.Builder getUserStatusBuilder() {
        
        onChanged();
        return getUserStatusFieldBuilder().getBuilder();
      }
      /**
       * <code>.ksoft.khulnasoft_common.UserStatus user_status = 1 [json_name = "userStatus"];</code>
       */
      public ksoft.khulnasoft_common.KhulnasoftCommon.UserStatusOrBuilder getUserStatusOrBuilder() {
        if (userStatusBuilder_ != null) {
          return userStatusBuilder_.getMessageOrBuilder();
        } else {
          return userStatus_ == null ?
              ksoft.khulnasoft_common.KhulnasoftCommon.UserStatus.getDefaultInstance() : userStatus_;
        }
      }
      /**
       * <code>.ksoft.khulnasoft_common.UserStatus user_status = 1 [json_name = "userStatus"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ksoft.khulnasoft_common.KhulnasoftCommon.UserStatus, ksoft.khulnasoft_common.KhulnasoftCommon.UserStatus.Builder, ksoft.khulnasoft_common.KhulnasoftCommon.UserStatusOrBuilder> 
          getUserStatusFieldBuilder() {
        if (userStatusBuilder_ == null) {
          userStatusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ksoft.khulnasoft_common.KhulnasoftCommon.UserStatus, ksoft.khulnasoft_common.KhulnasoftCommon.UserStatus.Builder, ksoft.khulnasoft_common.KhulnasoftCommon.UserStatusOrBuilder>(
                  getUserStatus(),
                  getParentForChildren(),
                  isClean());
          userStatus_ = null;
        }
        return userStatusBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ksoft.seat_management_pb.GetUserStatusResponse)
    }

    // @@protoc_insertion_point(class_scope:ksoft.seat_management_pb.GetUserStatusResponse)
    private static final ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse();
    }

    public static ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetUserStatusResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetUserStatusResponse>() {
      @java.lang.Override
      public GetUserStatusResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetUserStatusResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetUserStatusResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ksoft.seat_management_pb.SeatManagement.GetUserStatusResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RegisterUserRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ksoft.seat_management_pb.RegisterUserRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string firebase_id_token = 1 [json_name = "firebase_id_token"];</code>
     * @return The firebaseIdToken.
     */
    java.lang.String getFirebaseIdToken();
    /**
     * <code>string firebase_id_token = 1 [json_name = "firebase_id_token"];</code>
     * @return The bytes for firebaseIdToken.
     */
    com.google.protobuf.ByteString
        getFirebaseIdTokenBytes();
  }
  /**
   * Protobuf type {@code ksoft.seat_management_pb.RegisterUserRequest}
   */
  public static final class RegisterUserRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ksoft.seat_management_pb.RegisterUserRequest)
      RegisterUserRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RegisterUserRequest.newBuilder() to construct.
    private RegisterUserRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RegisterUserRequest() {
      firebaseIdToken_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RegisterUserRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ksoft.seat_management_pb.SeatManagement.internal_static_ksoft_seat_management_pb_RegisterUserRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ksoft.seat_management_pb.SeatManagement.internal_static_ksoft_seat_management_pb_RegisterUserRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ksoft.seat_management_pb.SeatManagement.RegisterUserRequest.class, ksoft.seat_management_pb.SeatManagement.RegisterUserRequest.Builder.class);
    }

    public static final int FIREBASE_ID_TOKEN_FIELD_NUMBER = 1;
    private volatile java.lang.Object firebaseIdToken_;
    /**
     * <code>string firebase_id_token = 1 [json_name = "firebase_id_token"];</code>
     * @return The firebaseIdToken.
     */
    @java.lang.Override
    public java.lang.String getFirebaseIdToken() {
      java.lang.Object ref = firebaseIdToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firebaseIdToken_ = s;
        return s;
      }
    }
    /**
     * <code>string firebase_id_token = 1 [json_name = "firebase_id_token"];</code>
     * @return The bytes for firebaseIdToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirebaseIdTokenBytes() {
      java.lang.Object ref = firebaseIdToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firebaseIdToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firebaseIdToken_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firebaseIdToken_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firebaseIdToken_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firebaseIdToken_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ksoft.seat_management_pb.SeatManagement.RegisterUserRequest)) {
        return super.equals(obj);
      }
      ksoft.seat_management_pb.SeatManagement.RegisterUserRequest other = (ksoft.seat_management_pb.SeatManagement.RegisterUserRequest) obj;

      if (!getFirebaseIdToken()
          .equals(other.getFirebaseIdToken())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIREBASE_ID_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getFirebaseIdToken().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ksoft.seat_management_pb.SeatManagement.RegisterUserRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ksoft.seat_management_pb.SeatManagement.RegisterUserRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ksoft.seat_management_pb.RegisterUserRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ksoft.seat_management_pb.RegisterUserRequest)
        ksoft.seat_management_pb.SeatManagement.RegisterUserRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ksoft.seat_management_pb.SeatManagement.internal_static_ksoft_seat_management_pb_RegisterUserRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ksoft.seat_management_pb.SeatManagement.internal_static_ksoft_seat_management_pb_RegisterUserRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ksoft.seat_management_pb.SeatManagement.RegisterUserRequest.class, ksoft.seat_management_pb.SeatManagement.RegisterUserRequest.Builder.class);
      }

      // Construct using ksoft.seat_management_pb.SeatManagement.RegisterUserRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        firebaseIdToken_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ksoft.seat_management_pb.SeatManagement.internal_static_ksoft_seat_management_pb_RegisterUserRequest_descriptor;
      }

      @java.lang.Override
      public ksoft.seat_management_pb.SeatManagement.RegisterUserRequest getDefaultInstanceForType() {
        return ksoft.seat_management_pb.SeatManagement.RegisterUserRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ksoft.seat_management_pb.SeatManagement.RegisterUserRequest build() {
        ksoft.seat_management_pb.SeatManagement.RegisterUserRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ksoft.seat_management_pb.SeatManagement.RegisterUserRequest buildPartial() {
        ksoft.seat_management_pb.SeatManagement.RegisterUserRequest result = new ksoft.seat_management_pb.SeatManagement.RegisterUserRequest(this);
        result.firebaseIdToken_ = firebaseIdToken_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ksoft.seat_management_pb.SeatManagement.RegisterUserRequest) {
          return mergeFrom((ksoft.seat_management_pb.SeatManagement.RegisterUserRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ksoft.seat_management_pb.SeatManagement.RegisterUserRequest other) {
        if (other == ksoft.seat_management_pb.SeatManagement.RegisterUserRequest.getDefaultInstance()) return this;
        if (!other.getFirebaseIdToken().isEmpty()) {
          firebaseIdToken_ = other.firebaseIdToken_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                firebaseIdToken_ = input.readStringRequireUtf8();

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object firebaseIdToken_ = "";
      /**
       * <code>string firebase_id_token = 1 [json_name = "firebase_id_token"];</code>
       * @return The firebaseIdToken.
       */
      public java.lang.String getFirebaseIdToken() {
        java.lang.Object ref = firebaseIdToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firebaseIdToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string firebase_id_token = 1 [json_name = "firebase_id_token"];</code>
       * @return The bytes for firebaseIdToken.
       */
      public com.google.protobuf.ByteString
          getFirebaseIdTokenBytes() {
        java.lang.Object ref = firebaseIdToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firebaseIdToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string firebase_id_token = 1 [json_name = "firebase_id_token"];</code>
       * @param value The firebaseIdToken to set.
       * @return This builder for chaining.
       */
      public Builder setFirebaseIdToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firebaseIdToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string firebase_id_token = 1 [json_name = "firebase_id_token"];</code>
       * @return This builder for chaining.
       */
      public Builder clearFirebaseIdToken() {
        
        firebaseIdToken_ = getDefaultInstance().getFirebaseIdToken();
        onChanged();
        return this;
      }
      /**
       * <code>string firebase_id_token = 1 [json_name = "firebase_id_token"];</code>
       * @param value The bytes for firebaseIdToken to set.
       * @return This builder for chaining.
       */
      public Builder setFirebaseIdTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firebaseIdToken_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ksoft.seat_management_pb.RegisterUserRequest)
    }

    // @@protoc_insertion_point(class_scope:ksoft.seat_management_pb.RegisterUserRequest)
    private static final ksoft.seat_management_pb.SeatManagement.RegisterUserRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ksoft.seat_management_pb.SeatManagement.RegisterUserRequest();
    }

    public static ksoft.seat_management_pb.SeatManagement.RegisterUserRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RegisterUserRequest>
        PARSER = new com.google.protobuf.AbstractParser<RegisterUserRequest>() {
      @java.lang.Override
      public RegisterUserRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RegisterUserRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RegisterUserRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ksoft.seat_management_pb.SeatManagement.RegisterUserRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RegisterUserResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ksoft.seat_management_pb.RegisterUserResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string api_key = 1 [json_name = "api_key"];</code>
     * @return The apiKey.
     */
    java.lang.String getApiKey();
    /**
     * <code>string api_key = 1 [json_name = "api_key"];</code>
     * @return The bytes for apiKey.
     */
    com.google.protobuf.ByteString
        getApiKeyBytes();

    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code ksoft.seat_management_pb.RegisterUserResponse}
   */
  public static final class RegisterUserResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ksoft.seat_management_pb.RegisterUserResponse)
      RegisterUserResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RegisterUserResponse.newBuilder() to construct.
    private RegisterUserResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RegisterUserResponse() {
      apiKey_ = "";
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RegisterUserResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ksoft.seat_management_pb.SeatManagement.internal_static_ksoft_seat_management_pb_RegisterUserResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ksoft.seat_management_pb.SeatManagement.internal_static_ksoft_seat_management_pb_RegisterUserResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ksoft.seat_management_pb.SeatManagement.RegisterUserResponse.class, ksoft.seat_management_pb.SeatManagement.RegisterUserResponse.Builder.class);
    }

    public static final int API_KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object apiKey_;
    /**
     * <code>string api_key = 1 [json_name = "api_key"];</code>
     * @return The apiKey.
     */
    @java.lang.Override
    public java.lang.String getApiKey() {
      java.lang.Object ref = apiKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        apiKey_ = s;
        return s;
      }
    }
    /**
     * <code>string api_key = 1 [json_name = "api_key"];</code>
     * @return The bytes for apiKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getApiKeyBytes() {
      java.lang.Object ref = apiKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apiKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(apiKey_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, apiKey_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(apiKey_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, apiKey_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ksoft.seat_management_pb.SeatManagement.RegisterUserResponse)) {
        return super.equals(obj);
      }
      ksoft.seat_management_pb.SeatManagement.RegisterUserResponse other = (ksoft.seat_management_pb.SeatManagement.RegisterUserResponse) obj;

      if (!getApiKey()
          .equals(other.getApiKey())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + API_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getApiKey().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ksoft.seat_management_pb.SeatManagement.RegisterUserResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ksoft.seat_management_pb.SeatManagement.RegisterUserResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ksoft.seat_management_pb.SeatManagement.RegisterUserResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ksoft.seat_management_pb.RegisterUserResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ksoft.seat_management_pb.RegisterUserResponse)
        ksoft.seat_management_pb.SeatManagement.RegisterUserResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ksoft.seat_management_pb.SeatManagement.internal_static_ksoft_seat_management_pb_RegisterUserResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ksoft.seat_management_pb.SeatManagement.internal_static_ksoft_seat_management_pb_RegisterUserResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ksoft.seat_management_pb.SeatManagement.RegisterUserResponse.class, ksoft.seat_management_pb.SeatManagement.RegisterUserResponse.Builder.class);
      }

      // Construct using ksoft.seat_management_pb.SeatManagement.RegisterUserResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        apiKey_ = "";

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ksoft.seat_management_pb.SeatManagement.internal_static_ksoft_seat_management_pb_RegisterUserResponse_descriptor;
      }

      @java.lang.Override
      public ksoft.seat_management_pb.SeatManagement.RegisterUserResponse getDefaultInstanceForType() {
        return ksoft.seat_management_pb.SeatManagement.RegisterUserResponse.getDefaultInstance();
      }

      @java.lang.Override
      public ksoft.seat_management_pb.SeatManagement.RegisterUserResponse build() {
        ksoft.seat_management_pb.SeatManagement.RegisterUserResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ksoft.seat_management_pb.SeatManagement.RegisterUserResponse buildPartial() {
        ksoft.seat_management_pb.SeatManagement.RegisterUserResponse result = new ksoft.seat_management_pb.SeatManagement.RegisterUserResponse(this);
        result.apiKey_ = apiKey_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ksoft.seat_management_pb.SeatManagement.RegisterUserResponse) {
          return mergeFrom((ksoft.seat_management_pb.SeatManagement.RegisterUserResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ksoft.seat_management_pb.SeatManagement.RegisterUserResponse other) {
        if (other == ksoft.seat_management_pb.SeatManagement.RegisterUserResponse.getDefaultInstance()) return this;
        if (!other.getApiKey().isEmpty()) {
          apiKey_ = other.apiKey_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                apiKey_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                name_ = input.readStringRequireUtf8();

                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object apiKey_ = "";
      /**
       * <code>string api_key = 1 [json_name = "api_key"];</code>
       * @return The apiKey.
       */
      public java.lang.String getApiKey() {
        java.lang.Object ref = apiKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          apiKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string api_key = 1 [json_name = "api_key"];</code>
       * @return The bytes for apiKey.
       */
      public com.google.protobuf.ByteString
          getApiKeyBytes() {
        java.lang.Object ref = apiKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          apiKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string api_key = 1 [json_name = "api_key"];</code>
       * @param value The apiKey to set.
       * @return This builder for chaining.
       */
      public Builder setApiKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        apiKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string api_key = 1 [json_name = "api_key"];</code>
       * @return This builder for chaining.
       */
      public Builder clearApiKey() {
        
        apiKey_ = getDefaultInstance().getApiKey();
        onChanged();
        return this;
      }
      /**
       * <code>string api_key = 1 [json_name = "api_key"];</code>
       * @param value The bytes for apiKey to set.
       * @return This builder for chaining.
       */
      public Builder setApiKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        apiKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ksoft.seat_management_pb.RegisterUserResponse)
    }

    // @@protoc_insertion_point(class_scope:ksoft.seat_management_pb.RegisterUserResponse)
    private static final ksoft.seat_management_pb.SeatManagement.RegisterUserResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ksoft.seat_management_pb.SeatManagement.RegisterUserResponse();
    }

    public static ksoft.seat_management_pb.SeatManagement.RegisterUserResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RegisterUserResponse>
        PARSER = new com.google.protobuf.AbstractParser<RegisterUserResponse>() {
      @java.lang.Override
      public RegisterUserResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RegisterUserResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RegisterUserResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ksoft.seat_management_pb.SeatManagement.RegisterUserResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ksoft_seat_management_pb_GetUserStatusRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ksoft_seat_management_pb_GetUserStatusRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ksoft_seat_management_pb_GetUserStatusResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ksoft_seat_management_pb_GetUserStatusResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ksoft_seat_management_pb_RegisterUserRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ksoft_seat_management_pb_RegisterUserRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ksoft_seat_management_pb_RegisterUserResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ksoft_seat_management_pb_RegisterUserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.ksoft/seat_management_pb/seat_manageme" +
      "nt.proto\022\030ksoft.seat_management_pb\032/ksof" +
      "t/khulnasoft_common/khulnasoft_common.pr" +
      "oto\032\037google/protobuf/timestamp.proto\"U\n\024" +
      "GetUserStatusRequest\022=\n\010metadata\030\001 \001(\0132!" +
      ".ksoft.khulnasoft_common.MetadataR\010metad" +
      "ata\"]\n\025GetUserStatusResponse\022D\n\013user_sta" +
      "tus\030\001 \001(\0132#.ksoft.khulnasoft_common.User" +
      "StatusR\nuserStatus\"C\n\023RegisterUserReques" +
      "t\022,\n\021firebase_id_token\030\001 \001(\tR\021firebase_i" +
      "d_token\"D\n\024RegisterUserResponse\022\030\n\007api_k" +
      "ey\030\001 \001(\tR\007api_key\022\022\n\004name\030\002 \001(\tR\004name2\374\001" +
      "\n\025SeatManagementService\022r\n\rGetUserStatus" +
      "\022..ksoft.seat_management_pb.GetUserStatu" +
      "sRequest\032/.ksoft.seat_management_pb.GetU" +
      "serStatusResponse\"\000\022o\n\014RegisterUser\022-.ks" +
      "oft.seat_management_pb.RegisterUserReque" +
      "st\032..ksoft.seat_management_pb.RegisterUs" +
      "erResponse\"\000B>Z<github.com/khulnasoft/de" +
      "vlabs/proto/ksoft/seat_management_pbb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ksoft.khulnasoft_common.KhulnasoftCommon.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_ksoft_seat_management_pb_GetUserStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ksoft_seat_management_pb_GetUserStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ksoft_seat_management_pb_GetUserStatusRequest_descriptor,
        new java.lang.String[] { "Metadata", });
    internal_static_ksoft_seat_management_pb_GetUserStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ksoft_seat_management_pb_GetUserStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ksoft_seat_management_pb_GetUserStatusResponse_descriptor,
        new java.lang.String[] { "UserStatus", });
    internal_static_ksoft_seat_management_pb_RegisterUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ksoft_seat_management_pb_RegisterUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ksoft_seat_management_pb_RegisterUserRequest_descriptor,
        new java.lang.String[] { "FirebaseIdToken", });
    internal_static_ksoft_seat_management_pb_RegisterUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ksoft_seat_management_pb_RegisterUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ksoft_seat_management_pb_RegisterUserResponse_descriptor,
        new java.lang.String[] { "ApiKey", "Name", });
    ksoft.khulnasoft_common.KhulnasoftCommon.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
