/*
 * Copyright KhulnaSoft, Ltd.
 */

package com.khulnasoft.intellij

import ksoft.khulnasoft_common_pb.KhulnasoftCommon

// Map from IntelliJ language ID to Khulnasoft language.
val LanguageMap =
    mapOf(
        "Blade" to KhulnasoftCommon.Language.LANGUAGE_BLADE,
        "C++" to KhulnasoftCommon.Language.LANGUAGE_C,
        "CMake" to KhulnasoftCommon.Language.LANGUAGE_CMAKE,
        "CoffeeScript" to KhulnasoftCommon.Language.LANGUAGE_COFFEESCRIPT,
        "C++" to KhulnasoftCommon.Language.LANGUAGE_CPP,
        "C#" to KhulnasoftCommon.Language.LANGUAGE_CSHARP,
        "CSS" to KhulnasoftCommon.Language.LANGUAGE_CSS,
        "Dart" to KhulnasoftCommon.Language.LANGUAGE_DART,
        "Dockerfile" to KhulnasoftCommon.Language.LANGUAGE_DOCKERFILE,
        "Elixir" to KhulnasoftCommon.Language.LANGUAGE_ELIXIR,
        "go" to KhulnasoftCommon.Language.LANGUAGE_GO,
        "Groovy" to KhulnasoftCommon.Language.LANGUAGE_GROOVY,
        "Handlebars" to KhulnasoftCommon.Language.LANGUAGE_HANDLEBARS,
        "HCL" to KhulnasoftCommon.Language.LANGUAGE_HCL,
        "HTML" to KhulnasoftCommon.Language.LANGUAGE_HTML,
        "Ini" to KhulnasoftCommon.Language.LANGUAGE_INI,
        "JAVA" to KhulnasoftCommon.Language.LANGUAGE_JAVA,
        "JavaScript JSX" to KhulnasoftCommon.Language.LANGUAGE_JAVASCRIPT,
        "JavaScript" to KhulnasoftCommon.Language.LANGUAGE_JAVASCRIPT,
        "ECMA Script Level 4" to KhulnasoftCommon.Language.LANGUAGE_JAVASCRIPT,
        "ECMAScript 6" to KhulnasoftCommon.Language.LANGUAGE_JAVASCRIPT,
        "JSON" to KhulnasoftCommon.Language.LANGUAGE_JSON,
        "JSON5" to KhulnasoftCommon.Language.LANGUAGE_JSON,
        "kotlin" to KhulnasoftCommon.Language.LANGUAGE_KOTLIN,
        "Latex" to KhulnasoftCommon.Language.LANGUAGE_LATEX,
        "LESS" to KhulnasoftCommon.Language.LANGUAGE_LESS,
        "Lua" to KhulnasoftCommon.Language.LANGUAGE_LUA,
        "Makefile" to KhulnasoftCommon.Language.LANGUAGE_MAKEFILE,
        "Markdown" to KhulnasoftCommon.Language.LANGUAGE_MARKDOWN,
        "ObjectiveC" to KhulnasoftCommon.Language.LANGUAGE_OBJECTIVEC,
        "protobuf" to KhulnasoftCommon.Language.LANGUAGE_PBTXT,
        "Perl5" to KhulnasoftCommon.Language.LANGUAGE_PERL,
        "PHP" to KhulnasoftCommon.Language.LANGUAGE_PHP,
        "PowerShell" to KhulnasoftCommon.Language.LANGUAGE_POWERSHELL,
        "protobuf" to KhulnasoftCommon.Language.LANGUAGE_PROTOBUF,
        "Python" to KhulnasoftCommon.Language.LANGUAGE_PYTHON,
        "python" to KhulnasoftCommon.Language.LANGUAGE_PYTHON,
        "R" to KhulnasoftCommon.Language.LANGUAGE_R,
        "ruby" to KhulnasoftCommon.Language.LANGUAGE_RUBY,
        "Rust" to KhulnasoftCommon.Language.LANGUAGE_RUST,
        "Scala" to KhulnasoftCommon.Language.LANGUAGE_SCALA,
        "Scala 3" to KhulnasoftCommon.Language.LANGUAGE_SCALA,
        "Scala 3 Worksheet" to KhulnasoftCommon.Language.LANGUAGE_SCALA,
        "SCSS" to KhulnasoftCommon.Language.LANGUAGE_SCSS,
        "Shell Script" to KhulnasoftCommon.Language.LANGUAGE_SHELL,
        "Solidity" to KhulnasoftCommon.Language.LANGUAGE_SOLIDITY,
        "SQL" to KhulnasoftCommon.Language.LANGUAGE_SQL,
        "SQLite" to KhulnasoftCommon.Language.LANGUAGE_SQL,
        "DBN-SQL" to KhulnasoftCommon.Language.LANGUAGE_SQL,
        "GenericSQL" to KhulnasoftCommon.Language.LANGUAGE_SQL,
        "MySQL" to KhulnasoftCommon.Language.LANGUAGE_SQL,
        "OracleSqlPlus" to KhulnasoftCommon.Language.LANGUAGE_SQL,
        "PostgreSQL" to KhulnasoftCommon.Language.LANGUAGE_SQL,
        "SvelteHTML" to KhulnasoftCommon.Language.LANGUAGE_SVELTE,
        "Swift" to KhulnasoftCommon.Language.LANGUAGE_SWIFT,
        "swift" to KhulnasoftCommon.Language.LANGUAGE_SWIFT,
        "TOML" to KhulnasoftCommon.Language.LANGUAGE_TOML,
        "TypeScript JSX" to KhulnasoftCommon.Language.LANGUAGE_TSX,
        "TypeScript" to KhulnasoftCommon.Language.LANGUAGE_TYPESCRIPT,
        "Vue" to KhulnasoftCommon.Language.LANGUAGE_VUE,
        "XML" to KhulnasoftCommon.Language.LANGUAGE_XML,
        "yaml" to KhulnasoftCommon.Language.LANGUAGE_YAML,
    )

val SupportedLanguages =
    setOf(
        KhulnasoftCommon.Language.LANGUAGE_APL,
        KhulnasoftCommon.Language.LANGUAGE_ASSEMBLY,
        KhulnasoftCommon.Language.LANGUAGE_ASTRO,
        KhulnasoftCommon.Language.LANGUAGE_BLADE,
        KhulnasoftCommon.Language.LANGUAGE_C,
        KhulnasoftCommon.Language.LANGUAGE_CLOJURE,
        KhulnasoftCommon.Language.LANGUAGE_CMAKE,
        KhulnasoftCommon.Language.LANGUAGE_COBOL,
        KhulnasoftCommon.Language.LANGUAGE_COFFEESCRIPT, // Adjacent to Khulnasoft language (JS)
        KhulnasoftCommon.Language.LANGUAGE_CPP,
        KhulnasoftCommon.Language.LANGUAGE_CSHARP,
        KhulnasoftCommon.Language.LANGUAGE_CRYSTAL,
        KhulnasoftCommon.Language.LANGUAGE_CSS,
        KhulnasoftCommon.Language.LANGUAGE_CUDACPP,
        KhulnasoftCommon.Language.LANGUAGE_DART,
        KhulnasoftCommon.Language.LANGUAGE_DOCKERFILE,
        KhulnasoftCommon.Language.LANGUAGE_ELIXIR,
        KhulnasoftCommon.Language.LANGUAGE_FORTRAN,
        KhulnasoftCommon.Language.LANGUAGE_FREEFORM,
        KhulnasoftCommon.Language.LANGUAGE_FSHARP,
        KhulnasoftCommon.Language.LANGUAGE_GDSCRIPT,
        KhulnasoftCommon.Language.LANGUAGE_GO,
        KhulnasoftCommon.Language.LANGUAGE_GRADLE,
        KhulnasoftCommon.Language.LANGUAGE_GROOVY,
        KhulnasoftCommon.Language.LANGUAGE_HANDLEBARS,
        KhulnasoftCommon.Language.LANGUAGE_HASKELL,
        KhulnasoftCommon.Language.LANGUAGE_HCL,
        KhulnasoftCommon.Language.LANGUAGE_HTML,
        KhulnasoftCommon.Language.LANGUAGE_INI,
        KhulnasoftCommon.Language.LANGUAGE_JAVA,
        KhulnasoftCommon.Language.LANGUAGE_JAVASCRIPT,
        KhulnasoftCommon.Language.LANGUAGE_JSON,
        KhulnasoftCommon.Language.LANGUAGE_JULIA,
        KhulnasoftCommon.Language.LANGUAGE_KOTLIN,
        KhulnasoftCommon.Language.LANGUAGE_LATEX,
        KhulnasoftCommon.Language.LANGUAGE_LESS, // Adjacent to Codegen language (JS)
        KhulnasoftCommon.Language.LANGUAGE_LISP,
        KhulnasoftCommon.Language.LANGUAGE_LUA,
        KhulnasoftCommon.Language.LANGUAGE_M68KASSEMBLY,
        KhulnasoftCommon.Language.LANGUAGE_MAKEFILE,
        KhulnasoftCommon.Language.LANGUAGE_MATLAB,
        KhulnasoftCommon.Language.LANGUAGE_MUMPS,
        KhulnasoftCommon.Language.LANGUAGE_NIM,
        KhulnasoftCommon.Language.LANGUAGE_OBJECTIVEC,
        KhulnasoftCommon.Language.LANGUAGE_OBJECTIVECPP,
        KhulnasoftCommon.Language.LANGUAGE_OCAML,
        KhulnasoftCommon.Language.LANGUAGE_PASCAL,
        KhulnasoftCommon.Language.LANGUAGE_PBTXT, // Empirically okay
        KhulnasoftCommon.Language.LANGUAGE_PERL,
        KhulnasoftCommon.Language.LANGUAGE_PHP,
        KhulnasoftCommon.Language.LANGUAGE_POWERSHELL,
        KhulnasoftCommon.Language.LANGUAGE_PROLOG,
        KhulnasoftCommon.Language.LANGUAGE_PROTOBUF, // Empirically okay
        KhulnasoftCommon.Language.LANGUAGE_PYTHON,
        KhulnasoftCommon.Language.LANGUAGE_R,
        KhulnasoftCommon.Language.LANGUAGE_RUBY,
        KhulnasoftCommon.Language.LANGUAGE_RUST,
        KhulnasoftCommon.Language.LANGUAGE_SAS,
        KhulnasoftCommon.Language.LANGUAGE_SASS, // Adjacent to Codegen language (JS)
        KhulnasoftCommon.Language.LANGUAGE_SCALA,
        KhulnasoftCommon.Language.LANGUAGE_SCSS,
        KhulnasoftCommon.Language.LANGUAGE_SHELL,
        KhulnasoftCommon.Language.LANGUAGE_SOLIDITY,
        KhulnasoftCommon.Language.LANGUAGE_SQL,
        KhulnasoftCommon.Language.LANGUAGE_STARLARK,
        KhulnasoftCommon.Language.LANGUAGE_SVELTE,
        KhulnasoftCommon.Language.LANGUAGE_SWIFT,
        KhulnasoftCommon.Language.LANGUAGE_TOML,
        KhulnasoftCommon.Language.LANGUAGE_TSX,
        KhulnasoftCommon.Language.LANGUAGE_TYPESCRIPT,
        KhulnasoftCommon.Language.LANGUAGE_UNIXASSEMBLY,
        KhulnasoftCommon.Language.LANGUAGE_VISUALBASIC,
        KhulnasoftCommon.Language.LANGUAGE_VUE,
        KhulnasoftCommon.Language.LANGUAGE_WEBASSEMBLY,
        KhulnasoftCommon.Language.LANGUAGE_YAML,
    )

fun getLanguage(language: String): KhulnasoftCommon.Language {
  return LanguageMap[language] ?: KhulnasoftCommon.Language.LANGUAGE_UNSPECIFIED
}

fun isWellSupportedLanguage(language: String): Boolean {
  return language == "*" || SupportedLanguages.contains(getLanguage(language))
}