name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [21]
        project: [
          'ai-spock-groovy-combo',
          'java-spring-refactor',
          'functional-test-rest-service',
          'smart-register',
          'pr-insight',
          'selenium-tests',
          'coverage-ai'
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: gradle

      - name: Build and Test
        run: |
          chmod +x gradlew
          ./gradlew clean build test integrationTest --stacktrace --info
        working-directory: intellij-projects/${{ matrix.project }}

      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Results (${{ matrix.project }})
          path: 'intellij-projects/${{ matrix.project }}/build/test-results/*/TEST-*.xml'
          reporter: java-junit
          fail-on-error: true

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.project }}
          path: intellij-projects/${{ matrix.project }}/build/

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Run Static Analysis
        run: |
          ./gradlew spotbugsMain spotbugsTest checkstyleMain checkstyleTest
        continue-on-error: true

      - name: Upload static analysis reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: static-analysis-reports
          path: build/reports

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Generate coverage report
        run: ./gradlew jacocoTestReport --stacktrace --info

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/reports/jacoco

  build-tools:
    name: Build Tool Examples
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Build Gradle examples
        run: |
          cd build-tool-projects/gradle/
          ./gradlew build

      - name: Validate Maven structure
        run: |
          cd build-tool-projects/maven/
          mvn validate

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          cd docker/
          docker build -t khulnasoft/react-weather-app:${{ github.sha }} -t khulnasoft/react-weather-app:latest .

      - name: Test Docker images
        run: |
          docker run --rm khulnasoft/react-weather-app:${{ github.sha }}

  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: [build-and-test, static-analysis, coverage]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html/
          cname: devlabs.khulnasoft.com
