// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ksoft/diff_action_pb/diff_action.proto

package ksoft.diff_action_pb;

public final class DiffAction {
  private DiffAction() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code ksoft.diff_action_pb.UnifiedDiffLineType}
   */
  public enum UnifiedDiffLineType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNIFIED_DIFF_LINE_TYPE_UNSPECIFIED = 0;</code>
     */
    UNIFIED_DIFF_LINE_TYPE_UNSPECIFIED(0),
    /**
     * <code>UNIFIED_DIFF_LINE_TYPE_INSERT = 1;</code>
     */
    UNIFIED_DIFF_LINE_TYPE_INSERT(1),
    /**
     * <code>UNIFIED_DIFF_LINE_TYPE_DELETE = 2;</code>
     */
    UNIFIED_DIFF_LINE_TYPE_DELETE(2),
    /**
     * <code>UNIFIED_DIFF_LINE_TYPE_UNCHANGED = 3;</code>
     */
    UNIFIED_DIFF_LINE_TYPE_UNCHANGED(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNIFIED_DIFF_LINE_TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int UNIFIED_DIFF_LINE_TYPE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>UNIFIED_DIFF_LINE_TYPE_INSERT = 1;</code>
     */
    public static final int UNIFIED_DIFF_LINE_TYPE_INSERT_VALUE = 1;
    /**
     * <code>UNIFIED_DIFF_LINE_TYPE_DELETE = 2;</code>
     */
    public static final int UNIFIED_DIFF_LINE_TYPE_DELETE_VALUE = 2;
    /**
     * <code>UNIFIED_DIFF_LINE_TYPE_UNCHANGED = 3;</code>
     */
    public static final int UNIFIED_DIFF_LINE_TYPE_UNCHANGED_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UnifiedDiffLineType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static UnifiedDiffLineType forNumber(int value) {
      switch (value) {
        case 0: return UNIFIED_DIFF_LINE_TYPE_UNSPECIFIED;
        case 1: return UNIFIED_DIFF_LINE_TYPE_INSERT;
        case 2: return UNIFIED_DIFF_LINE_TYPE_DELETE;
        case 3: return UNIFIED_DIFF_LINE_TYPE_UNCHANGED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UnifiedDiffLineType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UnifiedDiffLineType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UnifiedDiffLineType>() {
            public UnifiedDiffLineType findValueByNumber(int number) {
              return UnifiedDiffLineType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ksoft.diff_action_pb.DiffAction.getDescriptor().getEnumTypes().get(0);
    }

    private static final UnifiedDiffLineType[] VALUES = values();

    public static UnifiedDiffLineType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UnifiedDiffLineType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ksoft.diff_action_pb.UnifiedDiffLineType)
  }

  public interface UnifiedDiffOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ksoft.diff_action_pb.UnifiedDiff)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
     */
    java.util.List<ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine> 
        getLinesList();
    /**
     * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
     */
    ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine getLines(int index);
    /**
     * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
     */
    int getLinesCount();
    /**
     * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
     */
    java.util.List<? extends ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLineOrBuilder> 
        getLinesOrBuilderList();
    /**
     * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
     */
    ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLineOrBuilder getLinesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ksoft.diff_action_pb.UnifiedDiff}
   */
  public static final class UnifiedDiff extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ksoft.diff_action_pb.UnifiedDiff)
      UnifiedDiffOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UnifiedDiff.newBuilder() to construct.
    private UnifiedDiff(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UnifiedDiff() {
      lines_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UnifiedDiff();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ksoft.diff_action_pb.DiffAction.internal_static_ksoft_diff_action_pb_UnifiedDiff_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ksoft.diff_action_pb.DiffAction.internal_static_ksoft_diff_action_pb_UnifiedDiff_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ksoft.diff_action_pb.DiffAction.UnifiedDiff.class, ksoft.diff_action_pb.DiffAction.UnifiedDiff.Builder.class);
    }

    public interface UnifiedDiffLineOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string text = 1 [json_name = "text"];</code>
       * @return The text.
       */
      java.lang.String getText();
      /**
       * <code>string text = 1 [json_name = "text"];</code>
       * @return The bytes for text.
       */
      com.google.protobuf.ByteString
          getTextBytes();

      /**
       * <code>.ksoft.diff_action_pb.UnifiedDiffLineType type = 2 [json_name = "type"];</code>
       * @return The enum numeric value on the wire for type.
       */
      int getTypeValue();
      /**
       * <code>.ksoft.diff_action_pb.UnifiedDiffLineType type = 2 [json_name = "type"];</code>
       * @return The type.
       */
      ksoft.diff_action_pb.DiffAction.UnifiedDiffLineType getType();
    }
    /**
     * Protobuf type {@code ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine}
     */
    public static final class UnifiedDiffLine extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine)
        UnifiedDiffLineOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use UnifiedDiffLine.newBuilder() to construct.
      private UnifiedDiffLine(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private UnifiedDiffLine() {
        text_ = "";
        type_ = 0;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new UnifiedDiffLine();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ksoft.diff_action_pb.DiffAction.internal_static_ksoft_diff_action_pb_UnifiedDiff_UnifiedDiffLine_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ksoft.diff_action_pb.DiffAction.internal_static_ksoft_diff_action_pb_UnifiedDiff_UnifiedDiffLine_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine.class, ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine.Builder.class);
      }

      public static final int TEXT_FIELD_NUMBER = 1;
      private volatile java.lang.Object text_;
      /**
       * <code>string text = 1 [json_name = "text"];</code>
       * @return The text.
       */
      @java.lang.Override
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        }
      }
      /**
       * <code>string text = 1 [json_name = "text"];</code>
       * @return The bytes for text.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TYPE_FIELD_NUMBER = 2;
      private int type_;
      /**
       * <code>.ksoft.diff_action_pb.UnifiedDiffLineType type = 2 [json_name = "type"];</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.ksoft.diff_action_pb.UnifiedDiffLineType type = 2 [json_name = "type"];</code>
       * @return The type.
       */
      @java.lang.Override public ksoft.diff_action_pb.DiffAction.UnifiedDiffLineType getType() {
        @SuppressWarnings("deprecation")
        ksoft.diff_action_pb.DiffAction.UnifiedDiffLineType result = ksoft.diff_action_pb.DiffAction.UnifiedDiffLineType.valueOf(type_);
        return result == null ? ksoft.diff_action_pb.DiffAction.UnifiedDiffLineType.UNRECOGNIZED : result;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_);
        }
        if (type_ != ksoft.diff_action_pb.DiffAction.UnifiedDiffLineType.UNIFIED_DIFF_LINE_TYPE_UNSPECIFIED.getNumber()) {
          output.writeEnum(2, type_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, text_);
        }
        if (type_ != ksoft.diff_action_pb.DiffAction.UnifiedDiffLineType.UNIFIED_DIFF_LINE_TYPE_UNSPECIFIED.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine)) {
          return super.equals(obj);
        }
        ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine other = (ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine) obj;

        if (!getText()
            .equals(other.getText())) return false;
        if (type_ != other.type_) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getText().hashCode();
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine)
          ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLineOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ksoft.diff_action_pb.DiffAction.internal_static_ksoft_diff_action_pb_UnifiedDiff_UnifiedDiffLine_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ksoft.diff_action_pb.DiffAction.internal_static_ksoft_diff_action_pb_UnifiedDiff_UnifiedDiffLine_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine.class, ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine.Builder.class);
        }

        // Construct using ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          text_ = "";

          type_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ksoft.diff_action_pb.DiffAction.internal_static_ksoft_diff_action_pb_UnifiedDiff_UnifiedDiffLine_descriptor;
        }

        @java.lang.Override
        public ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine getDefaultInstanceForType() {
          return ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine.getDefaultInstance();
        }

        @java.lang.Override
        public ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine build() {
          ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine buildPartial() {
          ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine result = new ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine(this);
          result.text_ = text_;
          result.type_ = type_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine) {
            return mergeFrom((ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine other) {
          if (other == ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine.getDefaultInstance()) return this;
          if (!other.getText().isEmpty()) {
            text_ = other.text_;
            onChanged();
          }
          if (other.type_ != 0) {
            setTypeValue(other.getTypeValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  text_ = input.readStringRequireUtf8();

                  break;
                } // case 10
                case 16: {
                  type_ = input.readEnum();

                  break;
                } // case 16
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }

        private java.lang.Object text_ = "";
        /**
         * <code>string text = 1 [json_name = "text"];</code>
         * @return The text.
         */
        public java.lang.String getText() {
          java.lang.Object ref = text_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            text_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string text = 1 [json_name = "text"];</code>
         * @return The bytes for text.
         */
        public com.google.protobuf.ByteString
            getTextBytes() {
          java.lang.Object ref = text_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            text_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string text = 1 [json_name = "text"];</code>
         * @param value The text to set.
         * @return This builder for chaining.
         */
        public Builder setText(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          text_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string text = 1 [json_name = "text"];</code>
         * @return This builder for chaining.
         */
        public Builder clearText() {
          
          text_ = getDefaultInstance().getText();
          onChanged();
          return this;
        }
        /**
         * <code>string text = 1 [json_name = "text"];</code>
         * @param value The bytes for text to set.
         * @return This builder for chaining.
         */
        public Builder setTextBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          text_ = value;
          onChanged();
          return this;
        }

        private int type_ = 0;
        /**
         * <code>.ksoft.diff_action_pb.UnifiedDiffLineType type = 2 [json_name = "type"];</code>
         * @return The enum numeric value on the wire for type.
         */
        @java.lang.Override public int getTypeValue() {
          return type_;
        }
        /**
         * <code>.ksoft.diff_action_pb.UnifiedDiffLineType type = 2 [json_name = "type"];</code>
         * @param value The enum numeric value on the wire for type to set.
         * @return This builder for chaining.
         */
        public Builder setTypeValue(int value) {
          
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.ksoft.diff_action_pb.UnifiedDiffLineType type = 2 [json_name = "type"];</code>
         * @return The type.
         */
        @java.lang.Override
        public ksoft.diff_action_pb.DiffAction.UnifiedDiffLineType getType() {
          @SuppressWarnings("deprecation")
          ksoft.diff_action_pb.DiffAction.UnifiedDiffLineType result = ksoft.diff_action_pb.DiffAction.UnifiedDiffLineType.valueOf(type_);
          return result == null ? ksoft.diff_action_pb.DiffAction.UnifiedDiffLineType.UNRECOGNIZED : result;
        }
        /**
         * <code>.ksoft.diff_action_pb.UnifiedDiffLineType type = 2 [json_name = "type"];</code>
         * @param value The type to set.
         * @return This builder for chaining.
         */
        public Builder setType(ksoft.diff_action_pb.DiffAction.UnifiedDiffLineType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          type_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.ksoft.diff_action_pb.UnifiedDiffLineType type = 2 [json_name = "type"];</code>
         * @return This builder for chaining.
         */
        public Builder clearType() {
          
          type_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine)
      }

      // @@protoc_insertion_point(class_scope:ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine)
      private static final ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine();
      }

      public static ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<UnifiedDiffLine>
          PARSER = new com.google.protobuf.AbstractParser<UnifiedDiffLine>() {
        @java.lang.Override
        public UnifiedDiffLine parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<UnifiedDiffLine> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<UnifiedDiffLine> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int LINES_FIELD_NUMBER = 3;
    private java.util.List<ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine> lines_;
    /**
     * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
     */
    @java.lang.Override
    public java.util.List<ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine> getLinesList() {
      return lines_;
    }
    /**
     * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
     */
    @java.lang.Override
    public java.util.List<? extends ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLineOrBuilder> 
        getLinesOrBuilderList() {
      return lines_;
    }
    /**
     * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
     */
    @java.lang.Override
    public int getLinesCount() {
      return lines_.size();
    }
    /**
     * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
     */
    @java.lang.Override
    public ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine getLines(int index) {
      return lines_.get(index);
    }
    /**
     * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
     */
    @java.lang.Override
    public ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLineOrBuilder getLinesOrBuilder(
        int index) {
      return lines_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < lines_.size(); i++) {
        output.writeMessage(3, lines_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < lines_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, lines_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ksoft.diff_action_pb.DiffAction.UnifiedDiff)) {
        return super.equals(obj);
      }
      ksoft.diff_action_pb.DiffAction.UnifiedDiff other = (ksoft.diff_action_pb.DiffAction.UnifiedDiff) obj;

      if (!getLinesList()
          .equals(other.getLinesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getLinesCount() > 0) {
        hash = (37 * hash) + LINES_FIELD_NUMBER;
        hash = (53 * hash) + getLinesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ksoft.diff_action_pb.DiffAction.UnifiedDiff parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ksoft.diff_action_pb.DiffAction.UnifiedDiff parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ksoft.diff_action_pb.DiffAction.UnifiedDiff parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ksoft.diff_action_pb.DiffAction.UnifiedDiff parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ksoft.diff_action_pb.DiffAction.UnifiedDiff parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ksoft.diff_action_pb.DiffAction.UnifiedDiff parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ksoft.diff_action_pb.DiffAction.UnifiedDiff parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ksoft.diff_action_pb.DiffAction.UnifiedDiff parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ksoft.diff_action_pb.DiffAction.UnifiedDiff parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ksoft.diff_action_pb.DiffAction.UnifiedDiff parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ksoft.diff_action_pb.DiffAction.UnifiedDiff parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ksoft.diff_action_pb.DiffAction.UnifiedDiff parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ksoft.diff_action_pb.DiffAction.UnifiedDiff prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ksoft.diff_action_pb.UnifiedDiff}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ksoft.diff_action_pb.UnifiedDiff)
        ksoft.diff_action_pb.DiffAction.UnifiedDiffOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ksoft.diff_action_pb.DiffAction.internal_static_ksoft_diff_action_pb_UnifiedDiff_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ksoft.diff_action_pb.DiffAction.internal_static_ksoft_diff_action_pb_UnifiedDiff_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ksoft.diff_action_pb.DiffAction.UnifiedDiff.class, ksoft.diff_action_pb.DiffAction.UnifiedDiff.Builder.class);
      }

      // Construct using ksoft.diff_action_pb.DiffAction.UnifiedDiff.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (linesBuilder_ == null) {
          lines_ = java.util.Collections.emptyList();
        } else {
          lines_ = null;
          linesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ksoft.diff_action_pb.DiffAction.internal_static_ksoft_diff_action_pb_UnifiedDiff_descriptor;
      }

      @java.lang.Override
      public ksoft.diff_action_pb.DiffAction.UnifiedDiff getDefaultInstanceForType() {
        return ksoft.diff_action_pb.DiffAction.UnifiedDiff.getDefaultInstance();
      }

      @java.lang.Override
      public ksoft.diff_action_pb.DiffAction.UnifiedDiff build() {
        ksoft.diff_action_pb.DiffAction.UnifiedDiff result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ksoft.diff_action_pb.DiffAction.UnifiedDiff buildPartial() {
        ksoft.diff_action_pb.DiffAction.UnifiedDiff result = new ksoft.diff_action_pb.DiffAction.UnifiedDiff(this);
        int from_bitField0_ = bitField0_;
        if (linesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            lines_ = java.util.Collections.unmodifiableList(lines_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.lines_ = lines_;
        } else {
          result.lines_ = linesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ksoft.diff_action_pb.DiffAction.UnifiedDiff) {
          return mergeFrom((ksoft.diff_action_pb.DiffAction.UnifiedDiff)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ksoft.diff_action_pb.DiffAction.UnifiedDiff other) {
        if (other == ksoft.diff_action_pb.DiffAction.UnifiedDiff.getDefaultInstance()) return this;
        if (linesBuilder_ == null) {
          if (!other.lines_.isEmpty()) {
            if (lines_.isEmpty()) {
              lines_ = other.lines_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLinesIsMutable();
              lines_.addAll(other.lines_);
            }
            onChanged();
          }
        } else {
          if (!other.lines_.isEmpty()) {
            if (linesBuilder_.isEmpty()) {
              linesBuilder_.dispose();
              linesBuilder_ = null;
              lines_ = other.lines_;
              bitField0_ = (bitField0_ & ~0x00000001);
              linesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLinesFieldBuilder() : null;
            } else {
              linesBuilder_.addAllMessages(other.lines_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 26: {
                ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine m =
                    input.readMessage(
                        ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine.parser(),
                        extensionRegistry);
                if (linesBuilder_ == null) {
                  ensureLinesIsMutable();
                  lines_.add(m);
                } else {
                  linesBuilder_.addMessage(m);
                }
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine> lines_ =
        java.util.Collections.emptyList();
      private void ensureLinesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          lines_ = new java.util.ArrayList<ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine>(lines_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine, ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine.Builder, ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLineOrBuilder> linesBuilder_;

      /**
       * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
       */
      public java.util.List<ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine> getLinesList() {
        if (linesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(lines_);
        } else {
          return linesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
       */
      public int getLinesCount() {
        if (linesBuilder_ == null) {
          return lines_.size();
        } else {
          return linesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
       */
      public ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine getLines(int index) {
        if (linesBuilder_ == null) {
          return lines_.get(index);
        } else {
          return linesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
       */
      public Builder setLines(
          int index, ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine value) {
        if (linesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinesIsMutable();
          lines_.set(index, value);
          onChanged();
        } else {
          linesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
       */
      public Builder setLines(
          int index, ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine.Builder builderForValue) {
        if (linesBuilder_ == null) {
          ensureLinesIsMutable();
          lines_.set(index, builderForValue.build());
          onChanged();
        } else {
          linesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
       */
      public Builder addLines(ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine value) {
        if (linesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinesIsMutable();
          lines_.add(value);
          onChanged();
        } else {
          linesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
       */
      public Builder addLines(
          int index, ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine value) {
        if (linesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinesIsMutable();
          lines_.add(index, value);
          onChanged();
        } else {
          linesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
       */
      public Builder addLines(
          ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine.Builder builderForValue) {
        if (linesBuilder_ == null) {
          ensureLinesIsMutable();
          lines_.add(builderForValue.build());
          onChanged();
        } else {
          linesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
       */
      public Builder addLines(
          int index, ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine.Builder builderForValue) {
        if (linesBuilder_ == null) {
          ensureLinesIsMutable();
          lines_.add(index, builderForValue.build());
          onChanged();
        } else {
          linesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
       */
      public Builder addAllLines(
          java.lang.Iterable<? extends ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine> values) {
        if (linesBuilder_ == null) {
          ensureLinesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, lines_);
          onChanged();
        } else {
          linesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
       */
      public Builder clearLines() {
        if (linesBuilder_ == null) {
          lines_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          linesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
       */
      public Builder removeLines(int index) {
        if (linesBuilder_ == null) {
          ensureLinesIsMutable();
          lines_.remove(index);
          onChanged();
        } else {
          linesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
       */
      public ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine.Builder getLinesBuilder(
          int index) {
        return getLinesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
       */
      public ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLineOrBuilder getLinesOrBuilder(
          int index) {
        if (linesBuilder_ == null) {
          return lines_.get(index);  } else {
          return linesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
       */
      public java.util.List<? extends ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLineOrBuilder> 
           getLinesOrBuilderList() {
        if (linesBuilder_ != null) {
          return linesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(lines_);
        }
      }
      /**
       * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
       */
      public ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine.Builder addLinesBuilder() {
        return getLinesFieldBuilder().addBuilder(
            ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine.getDefaultInstance());
      }
      /**
       * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
       */
      public ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine.Builder addLinesBuilder(
          int index) {
        return getLinesFieldBuilder().addBuilder(
            index, ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine.getDefaultInstance());
      }
      /**
       * <code>repeated .ksoft.diff_action_pb.UnifiedDiff.UnifiedDiffLine lines = 3 [json_name = "lines"];</code>
       */
      public java.util.List<ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine.Builder> 
           getLinesBuilderList() {
        return getLinesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine, ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine.Builder, ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLineOrBuilder> 
          getLinesFieldBuilder() {
        if (linesBuilder_ == null) {
          linesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine, ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLine.Builder, ksoft.diff_action_pb.DiffAction.UnifiedDiff.UnifiedDiffLineOrBuilder>(
                  lines_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          lines_ = null;
        }
        return linesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ksoft.diff_action_pb.UnifiedDiff)
    }

    // @@protoc_insertion_point(class_scope:ksoft.diff_action_pb.UnifiedDiff)
    private static final ksoft.diff_action_pb.DiffAction.UnifiedDiff DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ksoft.diff_action_pb.DiffAction.UnifiedDiff();
    }

    public static ksoft.diff_action_pb.DiffAction.UnifiedDiff getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UnifiedDiff>
        PARSER = new com.google.protobuf.AbstractParser<UnifiedDiff>() {
      @java.lang.Override
      public UnifiedDiff parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UnifiedDiff> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UnifiedDiff> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ksoft.diff_action_pb.DiffAction.UnifiedDiff getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DiffBlockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ksoft.diff_action_pb.DiffBlock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 start_line = 1 [json_name = "startLine"];</code>
     * @return The startLine.
     */
    int getStartLine();

    /**
     * <code>int32 end_line = 2 [json_name = "endLine"];</code>
     * @return The endLine.
     */
    int getEndLine();

    /**
     * <code>.ksoft.diff_action_pb.UnifiedDiff unified_diff = 3 [json_name = "unifiedDiff"];</code>
     * @return Whether the unifiedDiff field is set.
     */
    boolean hasUnifiedDiff();
    /**
     * <code>.ksoft.diff_action_pb.UnifiedDiff unified_diff = 3 [json_name = "unifiedDiff"];</code>
     * @return The unifiedDiff.
     */
    ksoft.diff_action_pb.DiffAction.UnifiedDiff getUnifiedDiff();
    /**
     * <code>.ksoft.diff_action_pb.UnifiedDiff unified_diff = 3 [json_name = "unifiedDiff"];</code>
     */
    ksoft.diff_action_pb.DiffAction.UnifiedDiffOrBuilder getUnifiedDiffOrBuilder();

    /**
     * <code>.ksoft.khulnasoft_common.Language from_language = 4 [json_name = "fromLanguage"];</code>
     * @return The enum numeric value on the wire for fromLanguage.
     */
    int getFromLanguageValue();
    /**
     * <code>.ksoft.khulnasoft_common.Language from_language = 4 [json_name = "fromLanguage"];</code>
     * @return The fromLanguage.
     */
    ksoft.khulnasoft_common.KhulnasoftCommon.Language getFromLanguage();

    /**
     * <code>.ksoft.khulnasoft_common.Language to_language = 5 [json_name = "toLanguage"];</code>
     * @return The enum numeric value on the wire for toLanguage.
     */
    int getToLanguageValue();
    /**
     * <code>.ksoft.khulnasoft_common.Language to_language = 5 [json_name = "toLanguage"];</code>
     * @return The toLanguage.
     */
    ksoft.khulnasoft_common.KhulnasoftCommon.Language getToLanguage();
  }
  /**
   * <pre>
   * Proto representation of a code block.
   * </pre>
   *
   * Protobuf type {@code ksoft.diff_action_pb.DiffBlock}
   */
  public static final class DiffBlock extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ksoft.diff_action_pb.DiffBlock)
      DiffBlockOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DiffBlock.newBuilder() to construct.
    private DiffBlock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DiffBlock() {
      fromLanguage_ = 0;
      toLanguage_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DiffBlock();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ksoft.diff_action_pb.DiffAction.internal_static_ksoft_diff_action_pb_DiffBlock_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ksoft.diff_action_pb.DiffAction.internal_static_ksoft_diff_action_pb_DiffBlock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ksoft.diff_action_pb.DiffAction.DiffBlock.class, ksoft.diff_action_pb.DiffAction.DiffBlock.Builder.class);
    }

    public static final int START_LINE_FIELD_NUMBER = 1;
    private int startLine_;
    /**
     * <code>int32 start_line = 1 [json_name = "startLine"];</code>
     * @return The startLine.
     */
    @java.lang.Override
    public int getStartLine() {
      return startLine_;
    }

    public static final int END_LINE_FIELD_NUMBER = 2;
    private int endLine_;
    /**
     * <code>int32 end_line = 2 [json_name = "endLine"];</code>
     * @return The endLine.
     */
    @java.lang.Override
    public int getEndLine() {
      return endLine_;
    }

    public static final int UNIFIED_DIFF_FIELD_NUMBER = 3;
    private ksoft.diff_action_pb.DiffAction.UnifiedDiff unifiedDiff_;
    /**
     * <code>.ksoft.diff_action_pb.UnifiedDiff unified_diff = 3 [json_name = "unifiedDiff"];</code>
     * @return Whether the unifiedDiff field is set.
     */
    @java.lang.Override
    public boolean hasUnifiedDiff() {
      return unifiedDiff_ != null;
    }
    /**
     * <code>.ksoft.diff_action_pb.UnifiedDiff unified_diff = 3 [json_name = "unifiedDiff"];</code>
     * @return The unifiedDiff.
     */
    @java.lang.Override
    public ksoft.diff_action_pb.DiffAction.UnifiedDiff getUnifiedDiff() {
      return unifiedDiff_ == null ? ksoft.diff_action_pb.DiffAction.UnifiedDiff.getDefaultInstance() : unifiedDiff_;
    }
    /**
     * <code>.ksoft.diff_action_pb.UnifiedDiff unified_diff = 3 [json_name = "unifiedDiff"];</code>
     */
    @java.lang.Override
    public ksoft.diff_action_pb.DiffAction.UnifiedDiffOrBuilder getUnifiedDiffOrBuilder() {
      return getUnifiedDiff();
    }

    public static final int FROM_LANGUAGE_FIELD_NUMBER = 4;
    private int fromLanguage_;
    /**
     * <code>.ksoft.khulnasoft_common.Language from_language = 4 [json_name = "fromLanguage"];</code>
     * @return The enum numeric value on the wire for fromLanguage.
     */
    @java.lang.Override public int getFromLanguageValue() {
      return fromLanguage_;
    }
    /**
     * <code>.ksoft.khulnasoft_common.Language from_language = 4 [json_name = "fromLanguage"];</code>
     * @return The fromLanguage.
     */
    @java.lang.Override public ksoft.khulnasoft_common.KhulnasoftCommon.Language getFromLanguage() {
      @SuppressWarnings("deprecation")
      ksoft.khulnasoft_common.KhulnasoftCommon.Language result = ksoft.khulnasoft_common.KhulnasoftCommon.Language.valueOf(fromLanguage_);
      return result == null ? ksoft.khulnasoft_common.KhulnasoftCommon.Language.UNRECOGNIZED : result;
    }

    public static final int TO_LANGUAGE_FIELD_NUMBER = 5;
    private int toLanguage_;
    /**
     * <code>.ksoft.khulnasoft_common.Language to_language = 5 [json_name = "toLanguage"];</code>
     * @return The enum numeric value on the wire for toLanguage.
     */
    @java.lang.Override public int getToLanguageValue() {
      return toLanguage_;
    }
    /**
     * <code>.ksoft.khulnasoft_common.Language to_language = 5 [json_name = "toLanguage"];</code>
     * @return The toLanguage.
     */
    @java.lang.Override public ksoft.khulnasoft_common.KhulnasoftCommon.Language getToLanguage() {
      @SuppressWarnings("deprecation")
      ksoft.khulnasoft_common.KhulnasoftCommon.Language result = ksoft.khulnasoft_common.KhulnasoftCommon.Language.valueOf(toLanguage_);
      return result == null ? ksoft.khulnasoft_common.KhulnasoftCommon.Language.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (startLine_ != 0) {
        output.writeInt32(1, startLine_);
      }
      if (endLine_ != 0) {
        output.writeInt32(2, endLine_);
      }
      if (unifiedDiff_ != null) {
        output.writeMessage(3, getUnifiedDiff());
      }
      if (fromLanguage_ != ksoft.khulnasoft_common.KhulnasoftCommon.Language.LANGUAGE_UNSPECIFIED.getNumber()) {
        output.writeEnum(4, fromLanguage_);
      }
      if (toLanguage_ != ksoft.khulnasoft_common.KhulnasoftCommon.Language.LANGUAGE_UNSPECIFIED.getNumber()) {
        output.writeEnum(5, toLanguage_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (startLine_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, startLine_);
      }
      if (endLine_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, endLine_);
      }
      if (unifiedDiff_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getUnifiedDiff());
      }
      if (fromLanguage_ != ksoft.khulnasoft_common.KhulnasoftCommon.Language.LANGUAGE_UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, fromLanguage_);
      }
      if (toLanguage_ != ksoft.khulnasoft_common.KhulnasoftCommon.Language.LANGUAGE_UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, toLanguage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ksoft.diff_action_pb.DiffAction.DiffBlock)) {
        return super.equals(obj);
      }
      ksoft.diff_action_pb.DiffAction.DiffBlock other = (ksoft.diff_action_pb.DiffAction.DiffBlock) obj;

      if (getStartLine()
          != other.getStartLine()) return false;
      if (getEndLine()
          != other.getEndLine()) return false;
      if (hasUnifiedDiff() != other.hasUnifiedDiff()) return false;
      if (hasUnifiedDiff()) {
        if (!getUnifiedDiff()
            .equals(other.getUnifiedDiff())) return false;
      }
      if (fromLanguage_ != other.fromLanguage_) return false;
      if (toLanguage_ != other.toLanguage_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + START_LINE_FIELD_NUMBER;
      hash = (53 * hash) + getStartLine();
      hash = (37 * hash) + END_LINE_FIELD_NUMBER;
      hash = (53 * hash) + getEndLine();
      if (hasUnifiedDiff()) {
        hash = (37 * hash) + UNIFIED_DIFF_FIELD_NUMBER;
        hash = (53 * hash) + getUnifiedDiff().hashCode();
      }
      hash = (37 * hash) + FROM_LANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + fromLanguage_;
      hash = (37 * hash) + TO_LANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + toLanguage_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ksoft.diff_action_pb.DiffAction.DiffBlock parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ksoft.diff_action_pb.DiffAction.DiffBlock parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ksoft.diff_action_pb.DiffAction.DiffBlock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ksoft.diff_action_pb.DiffAction.DiffBlock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ksoft.diff_action_pb.DiffAction.DiffBlock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ksoft.diff_action_pb.DiffAction.DiffBlock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ksoft.diff_action_pb.DiffAction.DiffBlock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ksoft.diff_action_pb.DiffAction.DiffBlock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ksoft.diff_action_pb.DiffAction.DiffBlock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ksoft.diff_action_pb.DiffAction.DiffBlock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ksoft.diff_action_pb.DiffAction.DiffBlock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ksoft.diff_action_pb.DiffAction.DiffBlock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ksoft.diff_action_pb.DiffAction.DiffBlock prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Proto representation of a code block.
     * </pre>
     *
     * Protobuf type {@code ksoft.diff_action_pb.DiffBlock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ksoft.diff_action_pb.DiffBlock)
        ksoft.diff_action_pb.DiffAction.DiffBlockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ksoft.diff_action_pb.DiffAction.internal_static_ksoft_diff_action_pb_DiffBlock_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ksoft.diff_action_pb.DiffAction.internal_static_ksoft_diff_action_pb_DiffBlock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ksoft.diff_action_pb.DiffAction.DiffBlock.class, ksoft.diff_action_pb.DiffAction.DiffBlock.Builder.class);
      }

      // Construct using ksoft.diff_action_pb.DiffAction.DiffBlock.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        startLine_ = 0;

        endLine_ = 0;

        if (unifiedDiffBuilder_ == null) {
          unifiedDiff_ = null;
        } else {
          unifiedDiff_ = null;
          unifiedDiffBuilder_ = null;
        }
        fromLanguage_ = 0;

        toLanguage_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ksoft.diff_action_pb.DiffAction.internal_static_ksoft_diff_action_pb_DiffBlock_descriptor;
      }

      @java.lang.Override
      public ksoft.diff_action_pb.DiffAction.DiffBlock getDefaultInstanceForType() {
        return ksoft.diff_action_pb.DiffAction.DiffBlock.getDefaultInstance();
      }

      @java.lang.Override
      public ksoft.diff_action_pb.DiffAction.DiffBlock build() {
        ksoft.diff_action_pb.DiffAction.DiffBlock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ksoft.diff_action_pb.DiffAction.DiffBlock buildPartial() {
        ksoft.diff_action_pb.DiffAction.DiffBlock result = new ksoft.diff_action_pb.DiffAction.DiffBlock(this);
        result.startLine_ = startLine_;
        result.endLine_ = endLine_;
        if (unifiedDiffBuilder_ == null) {
          result.unifiedDiff_ = unifiedDiff_;
        } else {
          result.unifiedDiff_ = unifiedDiffBuilder_.build();
        }
        result.fromLanguage_ = fromLanguage_;
        result.toLanguage_ = toLanguage_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ksoft.diff_action_pb.DiffAction.DiffBlock) {
          return mergeFrom((ksoft.diff_action_pb.DiffAction.DiffBlock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ksoft.diff_action_pb.DiffAction.DiffBlock other) {
        if (other == ksoft.diff_action_pb.DiffAction.DiffBlock.getDefaultInstance()) return this;
        if (other.getStartLine() != 0) {
          setStartLine(other.getStartLine());
        }
        if (other.getEndLine() != 0) {
          setEndLine(other.getEndLine());
        }
        if (other.hasUnifiedDiff()) {
          mergeUnifiedDiff(other.getUnifiedDiff());
        }
        if (other.fromLanguage_ != 0) {
          setFromLanguageValue(other.getFromLanguageValue());
        }
        if (other.toLanguage_ != 0) {
          setToLanguageValue(other.getToLanguageValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                startLine_ = input.readInt32();

                break;
              } // case 8
              case 16: {
                endLine_ = input.readInt32();

                break;
              } // case 16
              case 26: {
                input.readMessage(
                    getUnifiedDiffFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 26
              case 32: {
                fromLanguage_ = input.readEnum();

                break;
              } // case 32
              case 40: {
                toLanguage_ = input.readEnum();

                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int startLine_ ;
      /**
       * <code>int32 start_line = 1 [json_name = "startLine"];</code>
       * @return The startLine.
       */
      @java.lang.Override
      public int getStartLine() {
        return startLine_;
      }
      /**
       * <code>int32 start_line = 1 [json_name = "startLine"];</code>
       * @param value The startLine to set.
       * @return This builder for chaining.
       */
      public Builder setStartLine(int value) {
        
        startLine_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 start_line = 1 [json_name = "startLine"];</code>
       * @return This builder for chaining.
       */
      public Builder clearStartLine() {
        
        startLine_ = 0;
        onChanged();
        return this;
      }

      private int endLine_ ;
      /**
       * <code>int32 end_line = 2 [json_name = "endLine"];</code>
       * @return The endLine.
       */
      @java.lang.Override
      public int getEndLine() {
        return endLine_;
      }
      /**
       * <code>int32 end_line = 2 [json_name = "endLine"];</code>
       * @param value The endLine to set.
       * @return This builder for chaining.
       */
      public Builder setEndLine(int value) {
        
        endLine_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 end_line = 2 [json_name = "endLine"];</code>
       * @return This builder for chaining.
       */
      public Builder clearEndLine() {
        
        endLine_ = 0;
        onChanged();
        return this;
      }

      private ksoft.diff_action_pb.DiffAction.UnifiedDiff unifiedDiff_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ksoft.diff_action_pb.DiffAction.UnifiedDiff, ksoft.diff_action_pb.DiffAction.UnifiedDiff.Builder, ksoft.diff_action_pb.DiffAction.UnifiedDiffOrBuilder> unifiedDiffBuilder_;
      /**
       * <code>.ksoft.diff_action_pb.UnifiedDiff unified_diff = 3 [json_name = "unifiedDiff"];</code>
       * @return Whether the unifiedDiff field is set.
       */
      public boolean hasUnifiedDiff() {
        return unifiedDiffBuilder_ != null || unifiedDiff_ != null;
      }
      /**
       * <code>.ksoft.diff_action_pb.UnifiedDiff unified_diff = 3 [json_name = "unifiedDiff"];</code>
       * @return The unifiedDiff.
       */
      public ksoft.diff_action_pb.DiffAction.UnifiedDiff getUnifiedDiff() {
        if (unifiedDiffBuilder_ == null) {
          return unifiedDiff_ == null ? ksoft.diff_action_pb.DiffAction.UnifiedDiff.getDefaultInstance() : unifiedDiff_;
        } else {
          return unifiedDiffBuilder_.getMessage();
        }
      }
      /**
       * <code>.ksoft.diff_action_pb.UnifiedDiff unified_diff = 3 [json_name = "unifiedDiff"];</code>
       */
      public Builder setUnifiedDiff(ksoft.diff_action_pb.DiffAction.UnifiedDiff value) {
        if (unifiedDiffBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          unifiedDiff_ = value;
          onChanged();
        } else {
          unifiedDiffBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ksoft.diff_action_pb.UnifiedDiff unified_diff = 3 [json_name = "unifiedDiff"];</code>
       */
      public Builder setUnifiedDiff(
          ksoft.diff_action_pb.DiffAction.UnifiedDiff.Builder builderForValue) {
        if (unifiedDiffBuilder_ == null) {
          unifiedDiff_ = builderForValue.build();
          onChanged();
        } else {
          unifiedDiffBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ksoft.diff_action_pb.UnifiedDiff unified_diff = 3 [json_name = "unifiedDiff"];</code>
       */
      public Builder mergeUnifiedDiff(ksoft.diff_action_pb.DiffAction.UnifiedDiff value) {
        if (unifiedDiffBuilder_ == null) {
          if (unifiedDiff_ != null) {
            unifiedDiff_ =
              ksoft.diff_action_pb.DiffAction.UnifiedDiff.newBuilder(unifiedDiff_).mergeFrom(value).buildPartial();
          } else {
            unifiedDiff_ = value;
          }
          onChanged();
        } else {
          unifiedDiffBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ksoft.diff_action_pb.UnifiedDiff unified_diff = 3 [json_name = "unifiedDiff"];</code>
       */
      public Builder clearUnifiedDiff() {
        if (unifiedDiffBuilder_ == null) {
          unifiedDiff_ = null;
          onChanged();
        } else {
          unifiedDiff_ = null;
          unifiedDiffBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ksoft.diff_action_pb.UnifiedDiff unified_diff = 3 [json_name = "unifiedDiff"];</code>
       */
      public ksoft.diff_action_pb.DiffAction.UnifiedDiff.Builder getUnifiedDiffBuilder() {
        
        onChanged();
        return getUnifiedDiffFieldBuilder().getBuilder();
      }
      /**
       * <code>.ksoft.diff_action_pb.UnifiedDiff unified_diff = 3 [json_name = "unifiedDiff"];</code>
       */
      public ksoft.diff_action_pb.DiffAction.UnifiedDiffOrBuilder getUnifiedDiffOrBuilder() {
        if (unifiedDiffBuilder_ != null) {
          return unifiedDiffBuilder_.getMessageOrBuilder();
        } else {
          return unifiedDiff_ == null ?
              ksoft.diff_action_pb.DiffAction.UnifiedDiff.getDefaultInstance() : unifiedDiff_;
        }
      }
      /**
       * <code>.ksoft.diff_action_pb.UnifiedDiff unified_diff = 3 [json_name = "unifiedDiff"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ksoft.diff_action_pb.DiffAction.UnifiedDiff, ksoft.diff_action_pb.DiffAction.UnifiedDiff.Builder, ksoft.diff_action_pb.DiffAction.UnifiedDiffOrBuilder> 
          getUnifiedDiffFieldBuilder() {
        if (unifiedDiffBuilder_ == null) {
          unifiedDiffBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ksoft.diff_action_pb.DiffAction.UnifiedDiff, ksoft.diff_action_pb.DiffAction.UnifiedDiff.Builder, ksoft.diff_action_pb.DiffAction.UnifiedDiffOrBuilder>(
                  getUnifiedDiff(),
                  getParentForChildren(),
                  isClean());
          unifiedDiff_ = null;
        }
        return unifiedDiffBuilder_;
      }

      private int fromLanguage_ = 0;
      /**
       * <code>.ksoft.khulnasoft_common.Language from_language = 4 [json_name = "fromLanguage"];</code>
       * @return The enum numeric value on the wire for fromLanguage.
       */
      @java.lang.Override public int getFromLanguageValue() {
        return fromLanguage_;
      }
      /**
       * <code>.ksoft.khulnasoft_common.Language from_language = 4 [json_name = "fromLanguage"];</code>
       * @param value The enum numeric value on the wire for fromLanguage to set.
       * @return This builder for chaining.
       */
      public Builder setFromLanguageValue(int value) {
        
        fromLanguage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ksoft.khulnasoft_common.Language from_language = 4 [json_name = "fromLanguage"];</code>
       * @return The fromLanguage.
       */
      @java.lang.Override
      public ksoft.khulnasoft_common.KhulnasoftCommon.Language getFromLanguage() {
        @SuppressWarnings("deprecation")
        ksoft.khulnasoft_common.KhulnasoftCommon.Language result = ksoft.khulnasoft_common.KhulnasoftCommon.Language.valueOf(fromLanguage_);
        return result == null ? ksoft.khulnasoft_common.KhulnasoftCommon.Language.UNRECOGNIZED : result;
      }
      /**
       * <code>.ksoft.khulnasoft_common.Language from_language = 4 [json_name = "fromLanguage"];</code>
       * @param value The fromLanguage to set.
       * @return This builder for chaining.
       */
      public Builder setFromLanguage(ksoft.khulnasoft_common.KhulnasoftCommon.Language value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        fromLanguage_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ksoft.khulnasoft_common.Language from_language = 4 [json_name = "fromLanguage"];</code>
       * @return This builder for chaining.
       */
      public Builder clearFromLanguage() {
        
        fromLanguage_ = 0;
        onChanged();
        return this;
      }

      private int toLanguage_ = 0;
      /**
       * <code>.ksoft.khulnasoft_common.Language to_language = 5 [json_name = "toLanguage"];</code>
       * @return The enum numeric value on the wire for toLanguage.
       */
      @java.lang.Override public int getToLanguageValue() {
        return toLanguage_;
      }
      /**
       * <code>.ksoft.khulnasoft_common.Language to_language = 5 [json_name = "toLanguage"];</code>
       * @param value The enum numeric value on the wire for toLanguage to set.
       * @return This builder for chaining.
       */
      public Builder setToLanguageValue(int value) {
        
        toLanguage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ksoft.khulnasoft_common.Language to_language = 5 [json_name = "toLanguage"];</code>
       * @return The toLanguage.
       */
      @java.lang.Override
      public ksoft.khulnasoft_common.KhulnasoftCommon.Language getToLanguage() {
        @SuppressWarnings("deprecation")
        ksoft.khulnasoft_common.KhulnasoftCommon.Language result = ksoft.khulnasoft_common.KhulnasoftCommon.Language.valueOf(toLanguage_);
        return result == null ? ksoft.khulnasoft_common.KhulnasoftCommon.Language.UNRECOGNIZED : result;
      }
      /**
       * <code>.ksoft.khulnasoft_common.Language to_language = 5 [json_name = "toLanguage"];</code>
       * @param value The toLanguage to set.
       * @return This builder for chaining.
       */
      public Builder setToLanguage(ksoft.khulnasoft_common.KhulnasoftCommon.Language value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        toLanguage_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ksoft.khulnasoft_common.Language to_language = 5 [json_name = "toLanguage"];</code>
       * @return This builder for chaining.
       */
      public Builder clearToLanguage() {
        
        toLanguage_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ksoft.diff_action_pb.DiffBlock)
    }

    // @@protoc_insertion_point(class_scope:ksoft.diff_action_pb.DiffBlock)
    private static final ksoft.diff_action_pb.DiffAction.DiffBlock DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ksoft.diff_action_pb.DiffAction.DiffBlock();
    }

    public static ksoft.diff_action_pb.DiffAction.DiffBlock getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DiffBlock>
        PARSER = new com.google.protobuf.AbstractParser<DiffBlock>() {
      @java.lang.Override
      public DiffBlock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DiffBlock> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DiffBlock> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ksoft.diff_action_pb.DiffAction.DiffBlock getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ksoft_diff_action_pb_UnifiedDiff_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ksoft_diff_action_pb_UnifiedDiff_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ksoft_diff_action_pb_UnifiedDiff_UnifiedDiffLine_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ksoft_diff_action_pb_UnifiedDiff_UnifiedDiffLine_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ksoft_diff_action_pb_DiffBlock_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ksoft_diff_action_pb_DiffBlock_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&ksoft/diff_action_pb/diff_action.proto" +
      "\022\024ksoft.diff_action_pb\032/ksoft/khulnasoft" +
      "_common/khulnasoft_common.proto\"\274\001\n\013Unif" +
      "iedDiff\022G\n\005lines\030\003 \003(\01321.ksoft.diff_acti" +
      "on_pb.UnifiedDiff.UnifiedDiffLineR\005lines" +
      "\032d\n\017UnifiedDiffLine\022\022\n\004text\030\001 \001(\tR\004text\022" +
      "=\n\004type\030\002 \001(\0162).ksoft.diff_action_pb.Uni" +
      "fiedDiffLineTypeR\004type\"\227\002\n\tDiffBlock\022\035\n\n" +
      "start_line\030\001 \001(\005R\tstartLine\022\031\n\010end_line\030" +
      "\002 \001(\005R\007endLine\022D\n\014unified_diff\030\003 \001(\0132!.k" +
      "soft.diff_action_pb.UnifiedDiffR\013unified" +
      "Diff\022F\n\rfrom_language\030\004 \001(\0162!.ksoft.khul" +
      "nasoft_common.LanguageR\014fromLanguage\022B\n\013" +
      "to_language\030\005 \001(\0162!.ksoft.khulnasoft_com" +
      "mon.LanguageR\ntoLanguage*\251\001\n\023UnifiedDiff" +
      "LineType\022&\n\"UNIFIED_DIFF_LINE_TYPE_UNSPE" +
      "CIFIED\020\000\022!\n\035UNIFIED_DIFF_LINE_TYPE_INSER" +
      "T\020\001\022!\n\035UNIFIED_DIFF_LINE_TYPE_DELETE\020\002\022$" +
      "\n UNIFIED_DIFF_LINE_TYPE_UNCHANGED\020\003B:Z8" +
      "github.com/khulnasoft/devlabs/proto/ksof" +
      "t/diff_action_pbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ksoft.khulnasoft_common.KhulnasoftCommon.getDescriptor(),
        });
    internal_static_ksoft_diff_action_pb_UnifiedDiff_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ksoft_diff_action_pb_UnifiedDiff_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ksoft_diff_action_pb_UnifiedDiff_descriptor,
        new java.lang.String[] { "Lines", });
    internal_static_ksoft_diff_action_pb_UnifiedDiff_UnifiedDiffLine_descriptor =
      internal_static_ksoft_diff_action_pb_UnifiedDiff_descriptor.getNestedTypes().get(0);
    internal_static_ksoft_diff_action_pb_UnifiedDiff_UnifiedDiffLine_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ksoft_diff_action_pb_UnifiedDiff_UnifiedDiffLine_descriptor,
        new java.lang.String[] { "Text", "Type", });
    internal_static_ksoft_diff_action_pb_DiffBlock_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ksoft_diff_action_pb_DiffBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ksoft_diff_action_pb_DiffBlock_descriptor,
        new java.lang.String[] { "StartLine", "EndLine", "UnifiedDiff", "FromLanguage", "ToLanguage", });
    ksoft.khulnasoft_common.KhulnasoftCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
